name: Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run CLang lint checker
        uses: DoozyX/clang-format-lint-action@v0.10
        with:
          source: .
          extensions: c,h
          style: webkit
      - name: Build with CMake
        run: |
          mkdir build && cd build
          cmake ..
          make
